server:
  port: 8091

spring:
  application:
    name: audit-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-service:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
